version: '3.1'
services:
  mysql:
    # image:
    build: ./dockerfile/
    restart: always
    container_name: mysql_coursera
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passw
